"""Side-score machinery of ``dev/tta_side.py`` on a synthetic two-face slab (CPU only)."""

from __future__ import annotations

import os
import sys

import numpy as np
import pytest

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "dev"))

tta_side = pytest.importorskip("tta_side")


def synthetic_slab(nz: int = 32, ny: int = 48, nx: int = 48, y_in: int = 16, y_out: int = 28,
                   band_at: str = "in", band_half: int = 1) -> tuple[dict, np.ndarray]:
    """A flat sheet body between ``y_in`` and ``y_out`` (n_out = +y): the in face is the low-y
    plane, the out face the high-y plane.  Returns (faces dict, probability volume with the band
    hugging the requested face)."""
    yy = np.arange(ny)[None, :, None] * np.ones((nz, 1, nx))
    faces = {
        "sdf_in": (yy - y_in).astype(np.float32),
        "sdf_out": (yy - y_out).astype(np.float32),
        "face_in": np.zeros((nz, ny, nx), bool),
        "face_out": np.zeros((nz, ny, nx), bool),
        "supervise": np.ones((nz, ny, nx), bool),
    }
    faces["face_in"][:, y_in, :] = True
    faces["face_out"][:, y_out, :] = True
    centre = y_in if band_at == "in" else y_out
    prob = np.zeros((nz, ny, nx), np.float32)
    prob[:, centre - band_half:centre + band_half + 1, :] = 1.0
    return faces, prob


def test_side_score_one_when_band_on_in_face():
    faces, prob = synthetic_slab(band_at="in")
    m = tta_side.side_metrics(prob, faces)
    assert m["in_cov1"] == pytest.approx(1.0)
    assert m["out_cov1"] == pytest.approx(0.0)
    assert m["side1"] == pytest.approx(1.0)
    assert m["side3"] == pytest.approx(1.0)
    assert m["frac_closer_in"] == pytest.approx(1.0)


def test_side_score_zero_when_the_band_is_flipped_to_the_out_face():
    faces, prob = synthetic_slab(band_at="out")
    m = tta_side.side_metrics(prob, faces)
    assert m["in_cov1"] == pytest.approx(0.0)
    assert m["out_cov1"] == pytest.approx(1.0)
    assert m["side1"] == pytest.approx(0.0)
    assert m["frac_closer_in"] == pytest.approx(0.0)
    assert m["frac_closer_out"] == pytest.approx(1.0)


def test_averaging_both_sides_is_two_sided():
    """The mean of an in-face and an out-face band covers both faces: side score ~ 0.5."""
    faces, pin = synthetic_slab(band_at="in")
    _, pout = synthetic_slab(band_at="out")
    m = tta_side.side_metrics(0.5 * (pin + pout), faces)
    assert m["in_cov1"] == pytest.approx(1.0)
    assert m["out_cov1"] == pytest.approx(1.0)
    assert m["side1"] == pytest.approx(0.5)


def test_empty_band_is_neutral():
    faces, prob = synthetic_slab()
    m = tta_side.side_metrics(np.zeros_like(prob), faces)
    assert m["n_band"] == 0 and m["side1"] == 0.5


def test_classification_threshold_logic():
    c = tta_side.classify_side
    assert c(0.72, 0.72) == "preserving"           # the identity itself
    assert c(0.70, 0.72) == "preserving"           # >= 0.9 * 0.72 = 0.648 and >= 0.6
    assert c(0.65, 0.72) == "preserving"
    assert c(0.62, 0.72) == "flipping"             # below 0.9 * identity
    assert c(0.59, 0.62) == "flipping"             # above 0.9 * identity but below the 0.6 floor
    assert c(0.30, 0.72) == "flipping"
    assert c(0.90, 0.95) == "preserving"


def test_direction_rule_recovers_a_planted_direction():
    """Classes generated by sign(d . g d) for d = +y are recovered exactly."""
    from tsm import equivariance as E

    d = np.array([0.0, 1.0, 0.0])
    rows = []
    for g in E.OCT48:
        cl = E.classify(g)
        cl.update({"matrix": g.tolist(), "type": "oct",
                   "side_class": "preserving" if float(d @ (g @ d)) > 0 else "flipping"})
        rows.append(cl)
    out = tta_side.direction_rule(rows, extra=0)
    assert out["acc"] == pytest.approx(1.0)
    assert abs(float(np.dot(out["d"], d))) > 0.9
